services:
  - type: static
    name: costikfinans
    env: static
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    staticPublishPath: out
    headers:
      - path: "/*"
        name: "Cache-Control"
        value: "public, max-age=600"
    routes:
      - type: rewrite
        source: "/**"
        destination: "/index.html"